connect: {autoconnect: true, bind: 0.0.0.0, port: 23, server: mg.mud.de}
database: {dns: 'sqlite:///riso.db'}
gui:
  color: {bg: '#ffff00000000', text: '#bebebebebebe'}
name: Riso
room:
  desc:
    release_ende: Du bist nun im "Lang"modus
    release_ignore: Du bist nun im "Kurz"modus
    release_ignore_values: [und]
    release_parse: 'Es gibt zwei sichtbare Ausgaenge:'
    release_strip: '>., '
  directions:
  - alias: [kurz, n, lang, schau]
    direction: n
  - alias: [kurz, s, lang, schau]
    direction: s
socket: {ignore_unknown_chars: true}
